name: heladas
channels:
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - arrow=1.2.3=py310haa95532_0
  - astroid=2.11.7=py310haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py310haa95532_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py310h2bbff1b_1
  - beautifulsoup4=4.11.1=py310haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=22.6.0=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - chardet=4.0.0=py310haa95532_1003
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.5=py310haa95532_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=38.0.1=py310h21b164f_0
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py310haa95532_0
  - docutils=0.18.1=py310haa95532_3
  - entrypoints=0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flake8=4.0.1=pyhd3eb1b0_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - imagesize=1.4.1=py310haa95532_0
  - importlib-metadata=4.11.3=py310haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - inflection=0.5.1=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.15.2=py310haa95532_0
  - ipython=7.31.1=py310haa95532_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py310haa95532_1
  - jellyfish=0.9.0=py310h2bbff1b_0
  - jinja2=3.1.2=py310haa95532_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.16.0=py310haa95532_0
  - jupyter_client=7.4.7=py310haa95532_0
  - jupyter_core=4.11.2=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyring=23.4.0=py310haa95532_0
  - lazy-object-proxy=1.6.0=py310h2bbff1b_0
  - libclang=12.0.0=default_h627e005_2
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lxml=4.9.1=py310h1985fb9_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - mypy_extensions=0.4.3=py310haa95532_1
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.7.0=py310haa95532_0
  - nest-asyncio=1.5.5=py310haa95532_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.23.4=py310h60c9a35_0
  - numpy-base=1.23.4=py310h04254f7_0
  - numpydoc=1.5.0=py310haa95532_0
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.1=py310h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.9.0=py310haa95532_0
  - pcre=8.45=hd77b12b_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.2.2=py310haa95532_0
  - platformdirs=2.5.2=py310haa95532_0
  - pluggy=1.0.0=py310haa95532_1
  - ply=3.11=py310haa95532_0
  - powershell_shortcut=0.0.1=3
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py310h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.14.5=py310haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py310h8cc25b3_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyqtwebengine=5.15.7=py310hd77b12b_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.8=h966fe2a_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-lsp-black=1.2.1=py310haa95532_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.5.0=py310haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - pytz=2022.1=py310haa95532_0
  - pywin32=302=py310h2bbff1b_2
  - pywin32-ctypes=0.2.0=py310haa95532_1000
  - pyyaml=6.0=py310h2bbff1b_1
  - pyzmq=23.2.0=py310hd77b12b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_4
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.2=py310haa95532_0
  - qtpy=2.2.0=py310haa95532_0
  - qtwebkit=5.212=h3ad3cdb_4
  - requests=2.28.1=py310haa95532_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py310h2eaa2aa_1
  - setuptools=65.5.0=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py310haa95532_0
  - sphinx=5.0.2=py310haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.3.3=py310haa95532_0
  - spyder-kernels=2.3.3=py310haa95532_0
  - sqlite=3.40.0=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - tomlkit=0.11.1=py310haa95532_0
  - tornado=6.2=py310h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.4.0=py310haa95532_0
  - tzdata=2022f=h04d1e81_0
  - ujson=5.4.0=py310hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.13=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=2.1.6=py310haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - whatthepatch=1.0.2=py310haa95532_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - wrapt=1.14.1=py310h2bbff1b_0
  - xz=5.2.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.8.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - affine==2.3.1
    - aiobotocore==2.4.1
    - aiohttp==3.8.3
    - aioitertools==0.11.0
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - botocore==1.27.59
    - charset-normalizer==2.1.1
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contourpy==1.0.6
    - crontab==0.23.0
    - cycler==0.11.0
    - fiona==1.8.22
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - geopandas==0.12.1
    - jmespath==1.0.1
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - multidict==6.0.2
    - munch==2.5.0
    - pillow==9.3.0
    - pyproj==3.4.0
    - rasterio==1.3.4
    - rioxarray==0.13.1
    - rptree==0.1.1
    - s3fs==2022.11.0
    - schedule==1.1.0
    - scipy==1.9.3
    - shapely==1.8.5.post1
    - snuggs==1.4.7
    - xarray==2022.11.0
    - yarl==1.8.1
prefix: C:\Users\ganta\.conda\envs\heladas
